language: java

sudo: required

jdk:
- oraclejdk8

services:
  - docker

install:
  - sudo pip install nose2
  - git clone https://github.com/kt3k/coveralls-gradle-plugin.git

script:
  - make
  - make sdkbase

after_success:
- ./gradlew jacocoTestReport coveralls
